version: '3.8'

services:
  bot:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    container_name: buryat-bot
    restart: unless-stopped
    
    env_file:
      - .env
    
    environment:
      - NODE_ENV=production
    
    ports:
      - "8080:8080"
    
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"